@Library('devops-projects-shared-lib') _

pipeline {

    agent {
        label 'docker'
    }

    parameters {
        choice choices: ['no', 'yes'], description: 'Are you sure, you want to deploy?', name: 'action'       
    }

    environment {
        DOCKER_CREDENTIALS = credentials('docker_credentials')
    }

    stages{

        stage('git checkout'){            
                when { expression { params.action == 'create' } }
                steps {                
                    gitCheckout(
                        branch: 'main',
                        url: 'https://github.com/csnkarthik/microservices-python-app.git'
                    )
                }
        }
       
    }    
}